server:
  port: 8200
spring:
  application:
    name: app-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:9100/eureka
    register-with-eureka: true
    fetch-registry: true

