server:
  port: 9100
##定义服务名称
spring:
  application:
    name: euerka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    register-with-eureka: true
    fetch-registry: true