##服务端口号：
server:
  port: 8100
##定义服务名称
spring:
  application:
    name: euerka
eureka:
  instance:
    ##注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
      ##因为自己是注册中心，不需要注册自己（搭建eureka集群的时候需要开启——true）
    register-with-eureka: true
    ##因为自己是注册中心，不需检索服务（搭建eureka集群的时候需要开启——true）
    fetch-registry: true
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
    ##剔除失效服务间隔
    eviction-interval-timer-in-ms: 2000